var CardNames = [
"Absorption Barrier",
"Absorption Forcefield",
"Absorption Shield",
"Achawin",
"Acid Spewer",
"Acid Spout",
"Adytum",
"Aegis",
"Agrius",
"Agrius Exemplar",
"Agrius Maximus",
"Air Superior",
"Air Support",
"Alaric",
"Angelwing",
"Annelid Mass",
"Anvil",
"Apex",
"Apex Dynamo",
"Apex Overdrive",
"Apollo",
"Arcane Dreadship",
"Arthurian",
"Arthurian King",
"Arthurian Monarch",
"Ascaris",
"Ascaris (NA)",
"Assembly Plant",
"Atomic Silo",
"Ayrkrane",
"Ayrkrane Vik",
"Azure Inheritor",
"Azure Reaper",
"Azure Reveler",
"Banshee",
"Barracus",
"Barrage Bunker",
"Barrage Tank",
"Barricade Slasher",
"Bazooka Marine",
"Beam Gate",
"Beholder",
"Benediction",
"Blight Bulwark",
"Blight Crusher",
"Blight Demolisher",
"Blight Geyser",
"Blight Trampler",
"Blighted Obelisk",
"Blisandrake",
"Blisandro",
"Blitz",
"Blitz Armor",
"Blitz Guard",
"Blitz Plate",
"Blood Pool",
"Bloodsucker",
"Bolide Walker",
"Bolt Crag",
"Bombardment Tanks",
"Boot Camp",
"Brood Lackey",
"Brood Minion",
"Brood Mother",
"Brood Walker",
"Brutal Beholder",
"Bulldozer",
"Cannon Walker",
"Carbine",
"Carcass Scrounge",
"Carnage Predator",
"Cavern Smelter",
"Charigniter",
"Charincinerator",
"Charrionite",
"Chiron",
"Classified Rig",
"Colossal Titan",
"Colossus",
"Combat Specialist",
"Constantine",
"Contaminant Purge",
"Contaminant Purifier",
"Contaminant Scour",
"Conversion Hall",
"Corpulent Barrier",
"Corrupted Daemon",
"Covert Jet",
"Credo Defender",
"Crushing Anvil",
"Cryptic Niaq",
"Crystallus Apollo",
"Cyberius",
"Cyberpod",
"Cyberpod XR5",
"Cyrus",
"Daemon",
"Dawnbringer",
"Defiance",
"Delphan",
"Delphan Inflamed",
"Delphan the Furious",
"Deranged Malgoth",
"Despoil Predator",
"Devourer",
"Dignified Vigil",
"Disposal Keep",
"Dissection Laser",
"Divine Equalizer",
"Dominator",
"Draconian Matriarch",
"Draconian Queen",
"Draconian Sovereign",
"Dracorex",
"Dracorex (NA)",
"Dracus Wyrm",
"Dragoon",
"Drake",
"Drake Patroller",
"Drake Scouter",
"Dread Panzer",
"Dreadnaught",
"Dreadship",
"Drifter",
"Drop Base",
"Dutiful Veteran",
"Earnest Pursuer",
"Ectoplasm",
"Empress",
"Enclave Apparition",
"Enclave Mothership",
"Enclave Parasite",
"Enclave Remnant",
"Enclave Vestige",
"Enfeebler",
"Entrails Bog",
"Entrails Pool",
"Equalizer",
"Equipped Warehouse",
"Exalted Memorial",
"Excelsitus",
"Exogrunt",
"Fanatic",
"Feral Scorpion",
"Ferocious Brute",
"Fierce Brute",
"Fighter Jet",
"Flash Deity",
"Fleet Mothership",
"Forged Memorial",
"Forsaken Beetle",
"Fortified Cannons",
"Fortifier",
"Frigid Grip",
"Fusillade Bunker",
"Fusion Silo",
"Galereaver",
"Garrison Fortifier",
"Genetics Chasm",
"Genetics Pit",
"Genetics Portal",
"Ghastly Specter",
"Ghost",
"Ghoulish Specter",
"Glaive",
"Gloom Assailant",
"Glorious Vigil",
"Goliath",
"Goliath Nega",
"Goliath Zero",
"Gore Typhon",
"Gorivore",
"Gornivorous",
"Grand Templar",
"Grim Specter",
"Grunt",
"Grusk the Devastator",
"Grusk the Pummeller",
"Grusk the Thrasher",
"Gunjack",
"Hades",
"Hades Enraged",
"Halcyon",
"Haunted Keep",
"Havenship",
"Havoc",
"Havoc Alpha",
"Havoc Genesis",
"Headhunter",
"Heart Devourer",
"Heart Reaper",
"Heart Shredder",
"Heavy Troop",
"Hellion",
"Helmcraft",
"Hephatat",
"Hephatat Fury",
"High Templar",
"Holy Benediction",
"Honor Guard",
"Honor-Bound Veteran",
"Howling Malgoth",
"Hydra",
"Hydroblade",
"Hypastryx",
"Hypersonic Deity",
"Illustrious Helmcraft",
"Immense Ospry",
"Imperial APC",
"Incinerator Rig",
"Indebted Veteran",
"Indestructible Troop",
"Infantry",
"Inferno Rig",
"Interdictor",
"Interstellar Battery",
"Interstellar Cannon",
"Interstellar Mortar",
"Invasion Blockade",
"Ion Strykers",
"Iron Eagle",
"Iron Maiden",
"Ironclad Avatar",
"Ironclad Troop",
"Joltrek Barge",
"Joltrek Scow",
"Joltrek Skiff",
"Jotun",
"Katana",
"Knight",
"Krellus",
"Kronus",
"Lead Dozer",
"Lightning Crag",
"Locust Swarm",
"Lord Hades",
"Loyal Arrester",
"Lucina",
"Luminous Apollo",
"Lummox",
"Lustrous Dawnbringer",
"Mach Jet",
"Maion",
"Malgoth",
"Malika",
"Mammoth Titan",
"Mark of Hope",
"Masterwork Aegis",
"Mawcor",
"Mawgore",
"Mawnage",
"Medic",
"Memorial",
"Miasma",
"Microgen",
"Miradren",
"Missile Silo",
"Mobile Base",
"Mobile Bastion",
"Mobile Encampment",
"Mobile Fortress",
"Mobile Rampart",
"Moloch",
"Mortar Bunker",
"Mortar Mech",
"Mutant Borg",
"Mystic Obelisk",
"Narscious",
"Narscious the Eerie",
"Narscious the Horror",
"Neo Delver",
"Neo Excavator",
"Neocyte Cultivator",
"Neocyte Extractor",
"Neocyte Resonator",
"Nexor",
"Nexusisider",
"Nexusisite",
"Nimbus",
"Nimbus Wonder",
"Noble Defiance",
"Noxious Tank",
"Obsidian Construct",
"Obsidian Drillmine",
"Obsidian Forge",
"Octane",
"Omega",
"Omega Nexite",
"Omega Nexus",
"Omniphet",
"Omniseer",
"Opak",
"Ospry",
"Overwatcher",
"Pack Dozer",
"Pantheon",
"Pantheon Charged",
"Pantheon Core",
"Pantheon Disciple",
"Pantheon Mecha",
"Pantheon Progeny",
"Partisan",
"Pathrazer",
"Peacekeeper",
"Petrisis",
"Petrisis (NA)",
"Plated Defender",
"Poseidon",
"Predator",
"Primus",
"Primus Max",
"Pure Benediction",
"Pursuer",
"Pylon",
"Pyro Rig",
"Rabid Corruptor",
"Radiant Cultivator",
"Radiant Dawnbringer",
"Ragnalast",
"Ragnareck",
"Ragnarok",
"Raider Encampment",
"Rally Infantry",
"Rastax",
"Razogoth",
"Razogoth's Heir",
"Razogoth's Legacy",
"Razogoth's Majesty",
"Razoling",
"Razor Maiden",
"Reckless Fanatic",
"Reconnoiter",
"Redeemer",
"Regeneration Bay",
"Remote Rig",
"Revolution",
"Revolver",
"Rift Awakener",
"Rift Summoner",
"Rifter",
"Ronin",
"Rubble Rover",
"Rupture Ogre",
"Ruthless Brute",
"Sacred Equalizer",
"Sacred Sanctuary",
"Sanctuary",
"Savage Beholder",
"Scarab",
"Scavenger",
"Schism Ogre",
"Scorpinox",
"Sculpted Aegis",
"Secluded Rig",
"Selfless Soldier",
"Sentry",
"Serapherus",
"Shadow",
"Shining Sanctuary",
"Shrapnel Engine",
"Shredder",
"Shrine of Hope",
"Shuddering Keep",
"Sidoze",
"Signal Towers",
"Skull Core",
"SkyCom",
"SkyCom Complete",
"SkyCom Perfect",
"Slug Borg",
"Smog Tank",
"Soulsteel Bronco",
"Soulsteel Mount",
"Spectre",
"Speculus",
"Spire Invader",
"Spiteful Raptor",
"Spore Pod",
"Stag Beetle",
"Starformer",
"Stealth Dreadship",
"Stealthy Niaq",
"Steel Maiden",
"Stormreaver",
"Stormrunner",
"STOVL Admiral",
"STOVL Carrier",
"STOVL Royal",
"Stronghold Fortifier",
"Sulfuris Sentry",
"Sundering Ogre",
"Supersonic Deity",
"Support Mech",
"Sustained Nimbus",
"Swarmling",
"Swift Hellion",
"Swift Troops",
"Symbolic Helmcraft",
"Tabitha",
"Tabitha (NA)",
"Tainted Blade",
"Tantazuma",
"Tantzumeca",
"Tartarus Brood",
"Tartarus Obelisk",
"Tartarus Scion",
"Tazerecca",
"Tazerok",
"Tempest Hold",
"Templar",
"Terminator",
"Terminator Mech",
"Terminator X",
"Terraformer",
"Terrogor",
"Thunder Crag",
"Tiamat",
"Tiamat Destructor",
"Tiamat the Destroyer",
"Tikal",
"Tikalan",
"Titan",
"Toxic Tank",
"Trap Setter",
"Tunneller",
"Twinblade",
"Typhon Vex",
"Typhon's Beast",
"Tyr Cannon",
"Unholy Daemon",
"Utopia Beacon",
"Utopia Lantern",
"Utopia Pharos",
"Valence",
"Valencio",
"Valentina",
"Vaporwing",
"Vegawalker",
"Venomous Raptor",
"Vicious Borg",
"Vigil",
"Viliamos",
"Vilion",
"Vilius",
"Vyander",
"Warehouse",
"Windreaver",
"Worldformer",
"Wurmsleth",
"Wurmsleth Infested",
"Wurmsleth Plagued",
"Xaedan",
"Xeno Mauler",
"Xeno Mothership",
"Xeno Overlord",
"Xeno Singularis",
"Xeno Suzerain",
"Yobediah",
"Yobedisect",
"Yurich",
"Zarak",
"Zarak Critical",
"Zarak Overcharged",
"Zealous Pursuer",
"Zephyr Superior",
"Zodiac",
"Zodiac Harbinger",
"Nephele",
"Warp Sculptor",
"Rendering Plant",
"Render",
"Herald",
"Gasher",
"Mending Sanctum",
"Relay Station",
"Thule Hound",
"Quadrishot",
"Spliced Gasher",
"Experiment Gasher",
"Renew Sanctum",
"Recovery Sanctum",
"Transit Station",
"Flux Station",
"Thule Mongrel",
"Thule Ravager",
"Nephelan",
"Nephelasus",
"Warp Fuser",
"Warp Alchemist",
"Processing Plant",
"Fusion Plant",
"Loaded Warehouse",
"Rampage",
"Rampage Rumbler",
"Pantheon Zealot",
"Sabre",
"Hornet Drones",
"General Agmeus",
"Vargas",
"Aria"
]